name: Laravel CI

# okidač - ova akcija će se pokrenuti na svaki 'push' na 'main' granu i na svaki 'pull request' koji cilja 'main' granu
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# dozvole za GITHUB_TOKEN za deployment (ako će trebati kasnije)
permissions:
  contents: read

jobs:
  laravel-tests:
    # definiramo na kojem operativnom sustavu će se posao izvršavati
    runs-on: ubuntu-latest

    # koraci (steps) koje treba izvršiti redom
    steps:
      # preuzimanje koda - koristi gotovu akciju 'actions/checkout' da preuzme kod iz repozitorija
      - name: Checkout code
        uses: actions/checkout@v4

      # postavljanje PHP okruženja - koristimo gotovu akciju za postavljanje specifične verzije PHP-a
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # možete odabrati verziju koja vam treba
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none

      # kopiranje .env datoteke - na CI serveru nemamo .env, pa kopiramo .env.example
      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Instalacija Composer ovisnosti - koristimo --no-progress i --prefer-dist za bržu instalaciju na CI
      - name: Install Dependencies
        run: composer install -q --no-progress --prefer-dist --optimize-autoloader

      # generiranje ključa aplikacije
      - name: Generate key
        run: php artisan key:generate
    
      # pokretanje migracija - postavljamo .env varijable za testiranje unutar samog koraka
      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: cicd
          DB_PORT: 3306
          DB_HOST: localhost
          DB_USERNAME: root
          DB_PASSWORD: 351211mm
        run: php artisan migrate

      # pokretanje testova
      - name: Execute tests (PHPUnit)
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: cicd
          DB_PORT: 3306
          DB_HOST: localhost
          DB_USERNAME: root
          DB_PASSWORD: 351211mm        
        run: php artisan test